Repository openedx/frontend-app-authn, pull requests merged in 2023-11, with the labels that each got.

#1099 fix: form submission when country is not requried
  src/register/data/utils.js
Labels: open-source-contribution, waiting for eng review

#1066 feat: implement SHOW_REGISTRATION_LINKS setting
  src/common-components/EnterpriseSSO.jsx
  src/config/index.js
  src/logistration/Logistration.jsx
  src/logistration/Logistration.test.jsx
Labels: open-source-contribution, waiting for eng review

#1072 fix: Enabling the ability to log in with a username consisting of 2 characters
  src/i18n/messages/ar.json
  src/i18n/messages/de_DE.json
  src/i18n/messages/es_419.json
  src/i18n/messages/fr.json
  src/i18n/messages/hi.json
  src/i18n/messages/it_IT.json
  src/i18n/messages/pt_PT.json
  src/i18n/messages/ru.json
  src/i18n/messages/uk.json
  src/i18n/messages/zh_CN.json
  src/login/LoginPage.jsx
  src/login/messages.jsx
  src/login/tests/LoginPage.test.jsx
Labels: open-source-contribution, waiting for eng review, backport

#1098 fix: Enabling the ability to log in with a username consisting of 2 c…
  src/i18n/messages/ar.json
  src/i18n/messages/de.json
  src/i18n/messages/de_DE.json
  src/i18n/messages/es_419.json
  src/i18n/messages/fa_IR.json
  src/i18n/messages/fr.json
  src/i18n/messages/fr_CA.json
  src/i18n/messages/hi.json
  src/i18n/messages/it.json
  src/i18n/messages/it_IT.json
  src/i18n/messages/pt.json
  src/i18n/messages/pt_PT.json
  src/i18n/messages/ru.json
  src/i18n/messages/uk.json
  src/i18n/messages/zh_CN.json
  src/login/LoginPage.jsx
  src/login/messages.jsx
  src/login/tests/LoginPage.test.jsx
Labels: open-source-contribution, waiting for eng review, backport

#1094 fix: content centering and z-index position on adaptation
  src/base-container/components/default-layout/MediumLayout.jsx
  src/base-container/components/default-layout/SmallLayout.jsx
  src/base-container/components/welcome-page-layout/SmallLayout.jsx
  src/sass/_base_component.scss
Labels: open-source-contribution, waiting for eng review

#1095 fix: content centering and z-index position on adaptation
  src/base-component/AuthSmallLayout.jsx
  src/base-component/MediumLayout.jsx
  src/base-component/SmallLayout.jsx
  src/sass/_base_component.scss
Labels: open-source-contribution, waiting for eng review, backport

#1093 fix: content centering and z-index position on adaptation
  src/base-container/components/default-layout/MediumLayout.jsx
  src/base-container/components/default-layout/SmallLayout.jsx
  src/base-container/components/welcome-page-layout/SmallLayout.jsx
  src/sass/_base_component.scss
Labels: open-source-contribution, waiting for eng review, backport

#1062 fix: Fixed spacing in tablet version
  src/base-container/components/default-layout/MediumLayout.jsx
  src/base-container/components/default-layout/SmallLayout.jsx
Labels: open-source-contribution

#1107 fix: Fixed spacing in tablet version (quince.master)
  src/base-container/components/default-layout/MediumLayout.jsx
  src/base-container/components/default-layout/SmallLayout.jsx
Labels: open-source-contribution, backport
