Repository openedx/frontend-app-authn, pull requests merged in 2023-03, with the labels that each got.

#761 chore(i18n): update translations
  src/i18n/messages/ar.json
  src/i18n/messages/de_DE.json
  src/i18n/messages/es_419.json
  src/i18n/messages/fr.json
  src/i18n/messages/hi.json
  src/i18n/messages/it_IT.json
  src/i18n/messages/pt_PT.json
  src/i18n/messages/ru.json
  src/i18n/messages/uk.json
  src/i18n/messages/zh_CN.json
Labels: core committer, open-source-contribution

#753 fix: incorrect link to password reset page
  src/login/LoginFailure.jsx
Labels: open-source-contribution

#759 fix: Remove horizontal scroll in windows (olive branch)
  src/sass/_style.scss
Labels: open-source-contribution, needs test run

#763 feat: displaying a support link on the welcome page
  src/welcome/ProgressiveProfiling.jsx
  src/welcome/tests/ProgressiveProfiling.test.jsx
Labels: open-source-contribution

#762 feat: displaying a support link on the welcome page
  src/progressive-profiling/ProgressiveProfiling.jsx
  src/progressive-profiling/tests/ProgressiveProfiling.test.jsx
Labels: open-source-contribution

#752 fix: incorrect link to password reset page
  src/login/LoginFailure.jsx
Labels: open-source-contribution

#792 fix: add Zendesk SDK rather than loading Zendesk by network call in A…
  .env.development
  package-lock.json
  package.json
  public/index.html
  src/MainApp.jsx
  src/common-components/Zendesk.jsx
  src/common-components/index.jsx
  src/common-components/messages.jsx
  src/common-components/tests/Zendesk.test.jsx
  src/common-components/tests/__snapshots__/Zendesk.test.jsx.snap
  src/config/index.js
Labels: autoupdate
