Repository openedx/frontend-app-authn, pull requests merged in 2023-04, with the labels that each got.

#747 chore(i18n): add more languages
  Makefile
  src/i18n/index.jsx
  src/i18n/messages/de.json
  src/i18n/messages/fr_CA.json
  src/i18n/messages/it.json
  src/i18n/messages/pt.json
Labels: open-source-contribution

#851 fix: nested components in CountryField
  .eslintrc.js
  src/register/data/constants.js
  src/register/registrationFields/CountryField.jsx
  src/register/tests/RegistrationPage.test.jsx
Labels: autoupdate

#849 fix: registration test coverage
  src/register/data/tests/reducers.test.js
  src/register/tests/RegistrationPage.test.jsx
Labels: autoupdate

#760 fix: Remove horizontal scroll in windows (master branch)
  src/sass/_style.scss
Labels: waiting on author, open-source-contribution, autoupdate
