Repository openedx/frontend-app-authn, pull requests merged in 2024-04, with the labels that each got.

#1208 [Backport] fix: Update custom SSO buttons to use brand colors
  src/sass/_style.scss
Labels: open-source-contribution, waiting for eng review, backport

#767 feat: Auth form visual enhancements (master)
  src/common-components/ThirdPartyAuth.jsx
Labels: open-source-contribution

#1225 feat: Hide preloaders for third party auth providers if they are disabled
  src/login/LoginPage.jsx
  src/register/components/ThirdPartyAuth.jsx
Labels: open-source-contribution, backport
